### ISSUE TITLE
Two-factor authentication Bug

### ISSUE THREAD

**Issue by sehathesam** [CosmosSoftware/AspNetCore.Identity.CosmosDb#9]
Hi 
I got an error on the Two-factor authentication.

after registering the user when you go to the profile page and click on Two-factor authentication you get this error :  

Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.NotSupportedException: Store does not implement IUserAuthenticatorKeyStore<User>.
         at Microsoft.AspNetCore.Identity.UserManager`1.GetAuthenticatorKeyStore()
         at Microsoft.AspNetCore.Identity.UserManager`1.GetAuthenticatorKeyAsync(TUser user)
         at CosmosDB_Test.Areas.Identity.Pages.Account.Manage.TwoFactorAuthenticationModel.OnGetAsync() in C:\Users\Sam\source\repos\CosmosDB_Test\CosmosDB_Test\Areas\Identity\Pages\Account\Manage\TwoFactorAuthentication.cshtml.cs:line 68

==========================================================
I use these packages:
```
<ItemGroup>
    <PackageReference Include="AspNetCore.Identity.CosmosDb" Version="2.0.18" />
    <PackageReference Include="AspNetCore.Identity.Services.SendGrid" Version="2.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Cosmos" Version="6.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.10" />
  </ItemGroup>
```

@toiyabe

**Comment by toiyabe** [comment]
Hello!

Thank you for sending in this issue. This helps improve this product!

Let me look into this and I will be getting back to you.  May I ask if you were implementing two factor authentication via Email or SMS?

Thank you!

-Eric

**Comment by toiyabe** [comment]
Looking into this further, the UserManager needs to implement the interface: IUserAuthenticatorKeyStore, which has two methods:

SetAuthenticatorKeyAsync()

and

GetAuthenticatorKeyAsync()

I'm working on that now.

-Eric

**Comment by toiyabe** [comment]
Just published release candidate [2.0.19-rc](https://www.nuget.org/packages/AspNetCore.Identity.CosmosDb/2.0.19-rc) in Nuget.  This includes implementation of two interfaces in the UserStore:

- IUserAuthenticatorKeyStore
- IUserTwoFactorRecoveryCodeStore

@sehathesam sehathesam, if you have a chance, could you please try this release candidate to validate the problem is fixed?

Thank you so much for pointing out this issue. It helps make this better.

-Eric

**Comment by toiyabe** [comment]
@sehathesam,

Today I’m writing unit tests to cover the new code. Once done and tests pass, I’ll publish a new release.

Thanks for your help.

-Eric

**Comment by sehathesam** [comment]
Hi

@toiyabe  I did not have access to the internet, sorry for the late reply.
I tested it now and it is completely correct.
Thank you so much, my friend

#woman life freedom
#mahsaamini
